[build]
  command = "npm run netlify:build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[build.processing]
  skip_processing = true

[build.plugins]
  package = "@netlify/plugin-nextjs"
  [build.plugins.inputs]
    enable = false

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
